apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: e-library
data:
  SERVER_PORT: "9091"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/e_library
