CREATE TYPE categories AS ENUM (
    'NOVEL',
    'THRILER',
    'HISTORY',
    'FANTASY',
    'BIOGRAPHY',
    'CLASSICS',
    'DRAMA'
    );

CREATE TYPE role AS ENUM (
    'ROLE_USER',
    'ROLE_LIBRARIAN'
    );

-- Tables
CREATE TABLE country
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255),
    continent VARCHAR(255)
);

CREATE TABLE author
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    surname    VARCHAR(255),
    country_id BIGINT REFERENCES country
);

CREATE TABLE book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255),
    category         categories NOT NULL,
    author_id        BIGINT REFERENCES author,
    available_copies INTEGER
);

CREATE TABLE book_history
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255),
    category         categories,
    author_id        BIGINT REFERENCES author,
    available_copies INTEGER,
    date_modified    TIMESTAMP,
    book_id          BIGINT REFERENCES book
);

CREATE TABLE shop_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255),
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE,
    role                       role
);

CREATE TABLE wishlist
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username VARCHAR(255) REFERENCES shop_users
);

CREATE TABLE wishlist_books
(
    wishlist_id BIGINT REFERENCES wishlist ON DELETE CASCADE,
    book_id     BIGINT REFERENCES book ON DELETE CASCADE,
    PRIMARY KEY (wishlist_id, book_id)
);
