apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: e-library
spec:
  selector:
    app: postgres
  ports:
    - port: 5432 #service port
      targetPort: 5432 #pod port
  clusterIP: None #headless svc